#!/usr/bin/env ruby
$:.unshift File.dirname(__FILE__)+"/../lib"

require 'metamuse'
require 'irb'

IRB.setup(nil)
irb = IRB::Irb.new

IRB.conf[:MAIN_CONTEXT] = irb.context

irb.context.evaluate("require 'irb/completion'", 0)
irb.context.evaluate("Metamuse.send(:register_api_keys)", 0)
irb.context.evaluate(%(
def reload!()
  $".grep(/^metamuse/).each {|e| load(e) }
end
), 0)

trap("SIGINT") do
  irb.signal_handle
end
catch(:IRB_EXIT) do
  irb.eval_input
end
